const lang = {
	en: {
		search: "Search",
		placeholder: "What would you like to search today",
		login: {
			name: "Full Name",
			email: "Email Address",
			password: "Password",
			signUp: "Sign Up",
			signIn: "Sign In",
			forgot: "Forgot Password?",
			newToNet: "New to Netflix",
			already: "Already registered",
			signUpNow: "Sign Up Now",
			signInNow: "Sign In Now",
			learn: "Learn more",
		},
	},
	hi: {
		search: "खोज",
		placeholder: "आज आप क्या खोजना चाहेंगे?",
		login: {
			name: "पूरा नाम",
			email: "मेल पता",
			password: "पासवर्ड",
			signUp: "साइन अप करें",
			signIn: "दाखिल करना",
			forgot: "पासवर्ड भूल गए?",
			newToNet: "नेटफ्लिक्स पर नया",
			already: "पहले से ही पंजीकृत",
			signUpNow: "अभी साइनअप करें",
			signInNow: "अब साइन इन करो",
			learn: "और अधिक जानें",
		},
	},
	te: {
		search: "వెతకండి",
		placeholder: "మీరు ఈరోజు ఏమి శోధించాలనుకుంటున్నారు",
		login: {
			name: "పూర్తి పేరు",
			email: "ఇమెయిల్ చిరునామా",
			password: "పాస్వర్డ్",
			signUp: "చేరడం",
			signIn: "సైన్ ఇన్ చేయండి",
			forgot: "పాస్‌వర్డ్ మర్చిపోయారా?",
			newToNet: "Netflixకి కొత్త",
			already: "ముందే నమోదుయాయ్యింది",
			signUpNow: "ఇప్పుడే సైన్ అప్",
			signInNow: "ఇప్పుడే సైన్ ఇన్ చేయండి",
			learn: "ఇంకా నేర్చుకో",
		},
	},
	ta: {
		search: "தேடல்",
		placeholder: "இன்று என்ன தேட விரும்புகிறீர்கள்",
		login: {
			name: "முழு பெயர்",
			email: "மின்னஞ்சல் முகவரி",
			password: "கடவுச்சொல்",
			signUp: "பதிவு செய்யவும்",
			signIn: "உள்நுழையவும்",
			forgot: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
			newToNet: "Netflix க்கு புதியது",
			already: "ஏற்கனவே பதிவு செய்யப்பட்டது",
			signUpNow: "இப்பொது பதிவு செய்",
			signInNow: "இப்போது உள்நுழையவும்",
			learn: "மேலும் அறிக",
		},
	},
	es: {
		search: "buscar",
		placeholder: "¿Qué te gustaría buscar hoy?",
		login: {
			name: "Nombre completo",
			email: "Dirección de correo electrónico",
			password: "Contraseña",
			signUp: "Inscribirse",
			signIn: "Iniciar sesión",
			forgot: "¿Has olvidado tu contraseña?",
			newToNet: "Nuevo en Netflix",
			already: "Ya registrado",
			signUpNow: "Regístrate ahora",
			signInNow: "Iniciar sesión ahora",
			learn: "Aprende más",
		},
	},
};

export default lang;
